language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

env:
  - DB_CONNECTION=mysql
  - DB_DATABASE=homestead
  - DB_USERNAME=root
  - DB_PASSWORD=

cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-progress --no-interaction --prefer-source --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install --global yarn
  - yarn
  - yarn dev

before_install:
  - mysql -e 'CREATE DATABASE homestead;'

script:
  - composer test

notifications:
  email: false