version: '3'

networks:
  internal:
    driver: bridge
  web:
    driver: bridge

volumes:
  redis:
    driver: local
  mariadb:
    driver: local

services:

  php-fpm:
    build: ./docker/php
    restart: unless-stopped
    volumes:
      - ./docker/php/php.dev.ini:/usr/local/etc/php/php.ini
      - ./api:/var/www/api
    expose:
      - 9000
    networks:
      - internal

  nginx:
    build: ./docker/nginx
    restart: unless-stopped
    volumes:
      - ./api:/var/www
      - ./docker/logs/nginx/:/var/log/nginx
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/ssl/:/etc/nginx/ssl
    ports:
      - 80:80
      - 81:81
      - 443:443
    links:
      - php-fpm
      - node
    networks:
      - internal
      - web

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - 6379:6379
    networks:
      - internal

  node:
    image: node:lts
    restart: unless-stopped
    command: npm run dev
    working_dir: /var/www/client
    volumes:
      - ./client:/var/www/client
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
    depends_on:
      - php-fpm
    networks:
      - web
