version: '3'

services:
  php:
    build: .
    container_name: laravel-portfolio
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
      - redis
      - mail
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - php
  mariadb:
    image: mariadb:10.3
    container_name: mysql
    working_dir: /var/www
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass secret
    volumes:
      - /data
    ports:
      - 6379:6379
  mail:
    image: mailhog/mailhog:latest
    container_name: mail
    ports:
      - 1025:1025
      - 8025:8025
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /sessions