export const SET_CATEGORIES = 'setCategories'
export const SET_PROJECTS = 'setProjects'
export const SET_LOCALE = 'SET_LOCALE'
export const SET_EDUCATION = 'setEducation'
export const SET_EXPERIENCE = 'setExperience'
export const SET_SETTINGS = 'setSettings'
