sudo: required
language: php
dist: bionic

php:
  - 7.3

services:
  - mysql

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - vendor
    - node_modules

before_script:
  - cp .env.travis.example .env
  - travis_retry composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install

before_install:
  - mysql -e 'CREATE DATABASE homestead;'
  - travis_retry composer self-update && composer --version

script:
  - composer test

notifications:
  email: false
